# Generated by Django 4.0.4 on 2022-05-18 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('family_members', '0002_family_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='kids_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
